### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by alejandroereyesb** [Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed4#1]
Hola!

Usemos este espacio para conocernos un poco más y presentarnos... :-)

Recordad que estos [issues](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed4/issues) nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más!

Podemos usar[ Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by beatrizsmerino** [comment]
Hola! Soy Bea, tengo 26 años y me presento un poco por aquí.

Al terminar el colegio hice un grado en Diseño Gráfico y me empecé a interesar por el diseño web. Estudie por mi cuenta y decidí hacer un curso online de HTML5, CSS3 y Javascript. Algo que suelo hacer mucho en mi tiempo libre es ver cursos online (Udemy, Edteam, Escuela It, Devcode...) :)

Al acabar la carrera me metí de lleno en la programación y me apunté a un Máster de HTML5, CSS3, Javascript, JQuery, PHP7 y SQL en el CICE para dar un salto y empezar a trabajar.
Después de aquello empecé las prácticas y desde entonces llevo casi 3 años trabajando en [Webpac](https://www.webpac.com/) como frontend developer.

El Javascript y yo nunca nos hemos llevado demasiado bien y con este curso espero que hagamos buenas migas.

**Algunos de mis skills**
- HTML5
- CSS3: SASS, BEM, ItCss, cross browsing, responsive web design
- Javascript: Jquery, JqueryUi, Vue
- API`s HTML5: Drag & drop...
- PHP 7 y SQL: structured programming, POO, MVC, CRUD, Workbench, MAMP, PhpMyAdmin
- Project management (trello, kanban, Git, Git Flow, Github, Sourcetree)
- Task runners: Gulp (npm)
- Code editors: SublimeText, Atom, Netbeans, Visual Studio Code, phpStorm.
- Design tools: Photoshop, Illustrator, InDesign...

**Os dejo por aquí algunos enlaces a redes sociales:**
- [Linkedin](https://www.linkedin.com/in/beatrizsmerino/)
- [Twitter](https://twitter.com/beatrizsmerino)
- [Codepen](https://codepen.io/beatrizsmerino/)
- [Github](https://github.com/beatrizsmerino)

**Y mi correo:**
beatrizsmerino@gmail.com

**Comment by jfernandezherranz** [comment]
Hola, yo soy **Joaquín**.
De pequeño me gustaba mucho jugar con las construcciones

![Image of lego](https://timedotcom.files.wordpress.com/2015/06/lego.jpg)

y ahora me divierto programando, es muy creativo y se parece bastante :smile:

He trabajado con [JQuery](https://jquery.com/) y [Angular](https://angular.io/), pero desde hace 2 años deseo entender bien [Javascript](https://developer.mozilla.org/es/docs/Web/JavaScript).

Hace 5 días he empezado el [Máster en Programación FullStack con JavaScript y Node.js](https://github.com/Fictizia/Master-en-Programacion-FullStack-con-JavaScript-y-Node.js_ed4) y estoy  emocionado con todo lo que vamos a aprender.

Os dejo mis enlaces a **redes sociales**:
* [Twitter](https://twitter.com/joaquin_fh)
* [Github](https://github.com/jfernandezherranz)

**Comment by egerman17** [comment]
Hola, yo soy Emilio, tengo 31 años y bueno os conto un poco de mí.

Ahora mismo trabajo tanto en una empresa de limpieza (nada que ver con esto jaja) y también en una pequeña empresa dedicada al mundo web (ayudando con algunos proyectos de maquetación).

Y bueno, empiezo de cero con programación para mejorar en este mundo de la informatica, y con mucha ilusión para sacar todo el trabajo adelante.

Mi correo:
Zanku17@gmail.com

**Comment by aurora-ms** [comment]
Bueno me presento un poco, tengo **25** años y soy de Toledo.
Estudie diseño gráfico y multimedia en ESNE aquí en Madrid.
Empecé a conocer lo que era el código en la ESO, haciendo los exámenes en papel lo cual al contrario que a los demás _me encantaba_.

Gracias a mis estudios y a los dos años de trabajo en una empresa publicitaria de Toledo me fui dando cuenta de que lo que me llamaba era la programación y aquí estoy a ver si consigo alcanzar mis metas.

Programas que “controlo”:

- pack adobe (Photoshop, illustrator, indesign...)
- construct
- pack autodesk (autocad, 3d Max...)

Y respecto a los lenguajes de programación:
- html
- css
- php ( en menor grado)
- un poco de JavaScript
Y ya está ;).

Un saludo 😄

**Comment by PedroZambra** [comment]
Hola! Me llamo **Pedro**, tengo 26 años y soy de Badajoz, he venido a Madrid principalmente a hacer este curso y seguir formándome.
Tengo el Grado Superior de Administración de Sistemas Informáticos en Red y un certificado de profesionalidad de desarrollo web, aunque llevaré solo como un año y medio dedicado y centrado en la programación que es lo que he descubierto que me encanta.

Mis aptitudes son:
* HTML
* CSS
* Bootstrap
* JavaScript
* AJAX
* React

Y me defiendo con:
* PHP
* SQL
* Java

Por mi [github](https://github.com/PedroZambra) tengo alguna cosilla subida.
Así como aficiones/gustos me encanta el deporte en especial la NBA, la cultura japonesa, el cine, los videojuegos y las nuevas tecnologías 😄 
Estoy ilusionado en seguir aprendiendo con el curso y seguir descubriendo JavaScript y Node.

Un saludo a todos!

**Comment by miguelmml** [comment]
Hola! soy Miguel y tengo 26 años.


Hace poco que he empezado a meterme en el mundo de la informática y me encanta! En programación parto de cero :S. Espero aprender un montón en el master, tengo muchas ganas de trabajar duro y empezar a programar . 

 Un saludo!!

**Comment by juanhhchu** [comment]
Hola , soy Juan, tengo 34 años.

Soy nuevo en todo esto del mundo de la programación, me empezó a interesar hace unos meses, creo que nunca es demasiado tarde para aprender cosas nuevas asi que pretendo empezar con este curso fullstack, y si todo va bien, aumentar mis conocimientos y mejorar mis skills.
Actualmente mis conocimientos sobre programación son de 0.01% y sobre MAC son muy básicos.

Un saludo a todo/todas  😄.
Que tengais un buen dia.

**Comment by rspineda** [comment]
Hola, Yo soy _*Ronald_*, tengo 31 años y como os comenté el primer día soy Psicologo y Profesor. 
Trabajo la mayor parte con adolescentes y me encanta mi trabajo, pero llevaba con la idea de hacer un master ya hace un par de años, bien del campo clínico, bien del campo académico o bien de algo que me atraía desde hace mucho tiempo pero que era romper completamente con lo que hago día a día y quizas renunciar a algo que me apasiona ahora mismo. Pero aplicadome una propia filosofía de vida que intento transmitir tanto a alumnos como a pacientes, me he lanzado a la aventura. 
Pero me he lanzado sabiendo que es un muy buen campo actualmente y que en esta escuela tendré una formación muy buena.  Eso hace  mas agradable la aventura.
De momento llevo sólo 2 semanas y me encanta, como es muy abstracto y requiere paciencia y exactitud en el código, todo va genial.
Conocimientos con los que parto, prácticamente nulos (sólo me metí html y css de unos libros en el verano), pero sé que soy muy bueno aprendiendo cosas y que lograré llevar el ritmo que me plantee el curso.
_Un saludo a todos los compi de clase!_   
Os dejo un fotito de mis futuros estados programando:
![codingstates](https://user-images.githubusercontent.com/56163866/66645566-19f56080-ec24-11e9-9af3-23677e718ecc.png)
